# Generated by Django 2.0.4 on 2018-09-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happenedat', models.DateTimeField()),
                ('typhoontime', models.TextField(default='1953061506')),
                ('intensity', models.FloatField(default=0)),
                ('is_change', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ('typhoonnumber', 'happenedat'),
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happenedat', models.DateTimeField()),
                ('typhoontime', models.TextField(default='1953061506')),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longitude', models.FloatField(default=0, null=True)),
                ('intensity', models.FloatField(default=0)),
                ('windspeed', models.FloatField(default=0)),
                ('airpressure', models.FloatField(default=0)),
                ('ordinarywindspeed', models.FloatField(default=0)),
                ('is_change', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ('typhoonnumber', 'happenedat'),
            },
        ),
        migrations.CreateModel(
            name='Typhoon',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('englishname', models.TextField(max_length=50)),
                ('startat', models.DateTimeField()),
                ('endat', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('is_delate', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('year', 'num'),
            },
        ),
        migrations.AddField(
            model_name='point',
            name='typhoonnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='台风编号', to='typhoon.Typhoon'),
        ),
        migrations.AddField(
            model_name='graphpoint',
            name='typhoonnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typhoon.Typhoon'),
        ),
    ]
