# Generated by Django 2.0.4 on 2018-09-24 00:29

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_friend', models.ForeignKey(on_delete=None, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('to_friend', models.ForeignKey(on_delete=None, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_cato_friendship',
            },
        ),
    ]
