# Generated by Django 2.0.4 on 2019-02-20 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suncreative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrecord',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
