# Generated by Django 2.0.4 on 2019-02-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suncreative', '0002_auto_20190220_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrecord',
            name='category',
            field=models.CharField(default='Default', max_length=30),
        ),
    ]
