# Generated by Django 2.2.13 on 2021-03-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suncreative', '0007_postrecord_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='文件夹', to='suncreative.MediaFolder'),
        ),
    ]
