# Generated by Django 2.2.13 on 2021-03-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suncreative', '0008_auto_20210306_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafolder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
